name: Publish to npm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --no-lockfile

      - name: Run lint
        run: yarn run lint

      - name: Run build
        run: yarn run compile

      - name: Publish package on NPM 📦
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
